
name: Publish to PyPI on tag

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - name: Inspect wheel METADATA
        run: |
          python - <<'PY'
          import glob, zipfile
          w = sorted(glob.glob('dist/*.whl'))[-1]
          z = zipfile.ZipFile(w)
          meta = [n for n in z.namelist() if n.endswith('.dist-info/METADATA')][0]
          print("WHEEL:", w)
          print(z.read(meta).decode('utf-8'))
          PY
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.5
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
